FROM node:22-slim

LABEL maintainer="MinIO Inc <dev@min.io>"

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      ca-certificates golang git make && \
    update-ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PATH=$PATH:/root/go/bin

RUN go install github.com/go-bindata/go-bindata/go-bindata@latest && \
    go install github.com/elazarl/go-bindata-assetfs/go-bindata-assetfs@latest

CMD ["bash"]